apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      app: mydeployment
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        app: mydeployment
    spec:
      containers:
        - name: nginx
          image: nginx
